### ISSUE TITLE
fail to build with channel not 3

### ISSUE THREAD

**Issue by Orig1n** [slothfulxtx/diff-gaussian-rasterization#27]
I changed NUM_CHANNELS to 32 in [config.h](https://github.com/slothfulxtx/diff-gaussian-rasterization/blob/main/cuda_rasterizer/config.h), then I failed to build with `pip install ./`, and it successed before the change.

here is the errors during the build:
```
Processing /home/diff-gaussian-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: diff_gauss
  Building wheel for diff_gauss (setup.py): started
  Building wheel for diff_gauss (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [816 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-310/diff_gauss
      copying diff_gauss/__init__.py -> build/lib.linux-x86_64-cpython-310/diff_gauss
      running build_ext
      /home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.7) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.7
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'diff_gauss._C' extension
      creating /home/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-310/cuda_rasterizer
      Emitting ninja build file /home/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-310/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/5] /usr/local/cuda-11.7/bin/nvcc  -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/TH -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/anaconda3/envs/torch112-cu116/include/python3.10 -c -c /home/diff-gaussian-rasterization/cuda_rasterizer/backward.cu -o /home/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-310/cuda_rasterizer/backward.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 -std=c++14
      FAILED: /home/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-310/cuda_rasterizer/backward.o
      /usr/local/cuda-11.7/bin/nvcc  -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/TH -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/anaconda3/envs/torch112-cu116/include/python3.10 -c -c /home/diff-gaussian-rasterization/cuda_rasterizer/backward.cu -o /home/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-310/cuda_rasterizer/backward.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 -std=c++14
       
      ptxas error   : Entry function '_Z10renderCUDAILj32EEvPK5uint2PKjiiiPKfPK6float2PK6float4S6_S6_S6_S6_S6_S4_S6_S6_S6_S6_S6_P6float3PSA_PfSG_SG_SG_SG_' uses too much shared data (0x13400 bytes, 0xc000 max)
      [2/5] /usr/local/cuda-11.7/bin/nvcc  -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/TH -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/anaconda3/envs/torch112-cu116/include/python3.10 -c -c /home/diff-gaussian-rasterization/cuda_rasterizer/forward.cu -o /home/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-310/cuda_rasterizer/forward.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 -std=c++14
      [3/5] /usr/local/cuda-11.7/bin/nvcc  -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/TH -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/anaconda3/envs/torch112-cu116/include/python3.10 -c -c /home/diff-gaussian-rasterization/cuda_rasterizer/rasterizer_impl.cu -o /home/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-310/cuda_rasterizer/rasterizer_impl.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 -std=c++14
      [4/5] c++ -MMD -MF /home/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-310/ext.o.d -pthread -B /home/anaconda3/envs/torch112-cu116/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/anaconda3/envs/torch112-cu116/include -fPIC -O2 -isystem /home/anaconda3/envs/torch112-cu116/include -fPIC -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/TH -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/anaconda3/envs/torch112-cu116/include/python3.10 -c -c /home/diff-gaussian-rasterization/ext.cpp -o /home/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-310/ext.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
      [5/5] /usr/local/cuda-11.7/bin/nvcc  -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/TH -I/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/anaconda3/envs/torch112-cu116/include/python3.10 -c -c /home/diff-gaussian-rasterization/rasterize_points.cu -o /home/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-310/rasterize_points.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -I/home/diff-gaussian-rasterization/third_party/glm/ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 -std=c++14
      /home/diff-gaussian-rasterization/rasterize_points.cu: In function ‘std::tuple<int, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor> RasterizeGaussiansCUDA(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, float, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, const at::Tensor&, const at::Tensor&, float, float, int, int, const at::Tensor&, int, const at::Tensor&, bool, bool)’:
      
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
          subprocess.run(
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/diff-gaussian-rasterization/setup.py", line 18, in <module>
          setup(
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 398, in run
          self.run_command("build")
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run
          _build_ext.run(self)
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
          objects = self.compiler.compile(
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/anaconda3/envs/torch112-cu116/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gauss
  Running setup.py clean for diff_gauss
Failed to build diff_gauss
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (diff_gauss)
```

**Comment by slothfulxtx** [comment]
Hi, there're too many code relying on RGB channel assumption. :( So if you wanna pass extra information into the rendering process and perform alpha-blending, I suggest you to treat them as per-Gaussian attributes instead of RGB channels.

**Comment by Orig1n** [comment]
Thanks but what did you mean by treating them as per-Gaussian attributes?

**Comment by slothfulxtx** [comment]
I guess you wanna pass an attribute defined on each Gaussians (i.e. RGB colors, normals, alpha value) to the rendering process, but it has 32 feature dims. I implement the rendering process (alpha-blending process) of this kind of attributes with the `extra_attrs` arguments [here](https://github.com/slothfulxtx/diff-gaussian-rasterization/blob/726449a8af5b933937acf1fc78deeee2beb0f879/diff_gauss/__init__.py#L31C5-L31C16). You don't need to modify the NUM_CHANNELS but pass it to the extra argument.
